spring:
  datasource:
    url: jdbc:h2:./app
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB
